### PR TITLE
Import ioc-indicators script

### LINKED ISSUE #82: Convert IoC definitions into CIA Indicators
Convert ThreatGRID "Indicators of Compromise" (IoCs) definitions into CIA Indicator objects for the alpha demo on Friday, March 11th.
[ioc-definitions.json.gz](https://github.com/threatgrid/cia/files/159226/ioc-definitions.json.gz)

### PR DESCRIPTION
**Pull request by polygloton**
Can be used on the command line like:

```bash
lein run -m ctia.import.threatgrid.ioc-indicators /Path/To/ioc-definitions.json http://localhost:3000 <api-key>
```

The api-key is optional.

Closes #82

### CODE REVIEW

**Comment by polygloton** [comment]
Need to implement symbolic naming in URLs

**Comment by saintx** [comment]
This is exactly what I need.  Very timely, thank you.

**Comment by saintx** [comment]
I tested the import ioc-indicators script on my local instance successfully, for the record.

**Comment by yogsototh** [comment]
look good to me 👍

**Comment by gbuisson** [comment]
looks good! 👍

**Comment by polygloton** [comment]
I am merging this now; Will get semantically valuable URLs implemented after the fact.  We need this in.

**Pull request merged**
