### PR TITLE
Filter incidents on timestamp not created

### PR DESCRIPTION
**Pull request by agzam**
> Close [advthreat/iroh#7917 — CTIA: filter incidents on timestamp instead of created](https://github.com/advthreat/iroh/issues/7917)
> Close https://github.com/advthreat/iroh/issues/8519

<a name="qa">[§](#qa)</a> QA
============================

Testing this feature essentially entails creating an incident (or multiple) and ensuring that its timestamp remains unchanged after modifying it.

1. Create a minimal Incident

```
POST https://intel.test.iroh.site/ctia/incident
Accept: application/json
Content-Type: application/json
Authorization: Bearer TOKEN

    {
    "incident_time" : {
        "opened" : "2016-02-11T00:40:48Z"
    },
    "status" : "Open",
    "confidence" : "High",
    "severity" : "High",
    "title" : "Some incident For Testing",
    "revision" : 3
    }
```
    
 This request returns an entity with an Id field that would be something like: 
`https://intel.test.iroh.site/ctia/incident/ctia/incident/incident-66c2b363-42a4-4e76-9e0b-00317ba1a29e`. We call these "long-ids".

2. Grab `incident-66c2b363-42a4-4e76-9e0b-00317ba1a29e` part of it. We internally call them "short-ids"

If you're testing with curl in the command line, you can pipe it to `jq` and `sed` like so:

```
curl 'https://intel.test.iroh.site/ctia/incident' \
-H 'Accept: application/json' \
-H 'Content-Type: application/json' \
-H 'Authorization: Bearer TOKEN' \
-X POST \
--data-raw '{
"incident_time" : {
    "opened" : "2016-02-11T00:40:48Z"
},
"status" : "Open",
"confidence" : "High",
"severity" : "High",
"title" : "Some Incident For Testing",
"revision" : 3
}
' | jq .id | sed 's|.*/||' | sed 's/"$//'
```

*jq is a cmd-line JSON processor that basically tells it to retrieve `id:` field value from the query result. 
sed - stands for "stream editor" and here it says to remove everything but the last segment of the long id url, and remove the trailing double quote as well*

3. Note the timestamp of the Incident you created

```
curl 'https://intel.test.iroh.site/ctia/incident/search/incident-66c2b363-42a4-4e76-9e0b-00317ba1a29e' \
-H 'Accept: application/json' \
-H 'Authorization: Bearer TOKEN' \
-H 'Content-Type: application/json' | jq .timestamp
```

*Remember, the last segment in the request should be the short id of the incident created* 

4. Modify created Incident

Patch the incident you just created, adjusting one of the fields, e.g., `status`. It was an Incident with the status `Open`, now change it to `Incident Reported`. Different possible values for Incident Status are [listed in CTIM](https://github.com/threatgrid/ctim/blob/master/src/ctim/schemas/vocabularies.cljc#L346)

```
    curl 'https://intel.test.iroh.site/ctia/incident/incident-66c2b363-42a4-4e76-9e0b-00317ba1a29e' \
    -H 'Accept: application/json' \
    -H 'Content-Type: application/json' \
    -H 'Authorization: Bearer TOKEN' \
    -X PATCH \
    --data-raw '{
    "status" : "Incident Reported"
    }'
```

5. Finally, compare the timestamp of the modified Incident with the timestamp at the time of the initial creation.

**The timestamps should match**

<a name="release-notes">[§](#release-notes)</a> Release Notes
=============================================================

```
intern: one-line description for internal eyes only.
public: one line description for public release notes.
```

<a name="squashed-commits">[§](#squashed-commits)</a> Squashed Commits
======================================================================

### CODE REVIEW

**Comment by agzam** [comment]
@ereteog can you please take a look, is that close to what you had in mind?

**Review by ereteog — COMMENTED** [review]
Yes it applies what I described.
Can you populate the QA section please?

**Comment by agzam** [comment]
@ereteog Oh, It looks like I still have to address the part where you said:

> Then we need to have from and to applied to timestamp instead of [the default created](https://github.com/threatgrid/ctia/blob/9134c455ef0c7f7da150359b209c6583449e7d48/src/ctia/http/routes/crud.clj#LL180C10-L180C20) by adding :date-field :timestamp [here](https://github.com/threatgrid/ctia/blob/9134c455ef0c7f7da150359b209c6583449e7d48/src/ctia/entity/incident.clj#L416).

I'm still not very sure what do we have to change for that. Maybe we should do it in a separate PR?

**Comment by ereteog** [comment]
> @ereteog Oh, It looks like I still have to address the part where you said:
> 
> > Then we need to have from and to applied to timestamp instead of [the default created](https://github.com/threatgrid/ctia/blob/9134c455ef0c7f7da150359b209c6583449e7d48/src/ctia/http/routes/crud.clj#LL180C10-L180C20) by adding :date-field :timestamp [here](https://github.com/threatgrid/ctia/blob/9134c455ef0c7f7da150359b209c6583449e7d48/src/ctia/entity/incident.clj#L416).
> 
> I'm still not very sure what do we have to change for that. Maybe we should do it in a separate PR?

Yes you can do it in a separate PR (I changed Close to Related)

**Review by ereteog — APPROVED** [review]
LGTM.
You should consider my remark to simplify the work of QA

**Comment by jamoser-cisco** [comment]
I wish all QA sections were so detailed, thanks @agzam!

I verified patching a couple of incidents alone does not change the timestamp, however I am able to PATCH the timestamp value itself.  Is this intended??

**Comment by jamoser-cisco** [comment]
@ereteog, maybe I should have tagged you to ask that?? After reading the linked tickets it seems agzam is no longer with Cisco??

**Comment by jamoser-cisco** [comment]
and it seems you answered that question in the same comment I learned that in... =)

**Comment by ereteog** [comment]
> I verified patching a couple of incidents alone does not change the timestamp, however I am able to PATCH the timestamp value itself. Is this intended??

Yes that's the right behaviour

**Pull request merged**
