### PR TITLE
ctim-64-fix: fix related to issue 64 of CTIM

### PR DESCRIPTION
**Pull request by yogsototh**
related to https://github.com/threatgrid/ctim/pull/109

### CODE REVIEW

**Comment by yogsototh** [comment]
Test won't pass before a 0.3.3-SNAPSHOT release will be pushed to clojars for CTIM

**Comment by polygloton** [comment]
Do you need me to push to clojars?

**Comment by polygloton** [comment]
Also I think we should make a release of CTIM (non-snapshot) whenever we are about to merge a new version into CTIA.  In other words, CTIA master never uses a CTIM snapshot version.  Snapshot is good enough in a branch (also good enough in a PR that is still "In Progress").

**Comment by polygloton** [comment]
Other than my comments above, this looks good to me!

**Pull request merged**
