### PR TITLE
Hooks with java and jar file examples

### LINKED ISSUE #159: Refactoring handlers to accomodate hooks, and events and stores
A discussion with the crew.

For CRUD operations, we would like the following "flow" within handlers.
 
## Creation and Update

  1. Realize the object from the inputs, using the existing "realize" functions.
    1. The realization function produced our initial, default StoredObject
    2. Call our "Realization" hooks, which may return a modified StoredObject
        - these are the before-create/update/delete hooks
  2. Wrap the StoredObject in the appropriate Event.
  3. Call the Event hooks, which cannot transform, and must all run succesfully (kafka feed...)
       - these are the after-create/update/delete-hooks, except those functions dont take events, they take the object itself.  This is a deviation
  4. Call the stores, passing in the StoredObject, to perform the operation, it must return succesfully
  5. Pass the Event (not just the StoredObject) on the core.async channel

## Deletion
  1. Replicate the realize- flow with a destroy- flow
  2. Product the Event, and it should contain the model, which is an optional field in the schema
  3. Call the Event hooks, which cannot transform, and must all run succesfully (kafka feed...)
  4. Call the stores delete/destroy, it must be successful
  5. Pass the Event on the core.async channel

## Realization Hooks
For every Stored Object type, we have a vector of Hook objects, modeled on GUNDAM hook.  Hooks are all "required" in that they must all return succesfully.  They must be run in a specific order, this allows the specification of hook order as a means of control flow configuration. Hooks can return a modified realized object.  If they return nil the current realized object is used.  They take the same parameter set as the realize functions.

## Commentary
Craig: Note that we isolate business logic in the realize and detroy steps, from the implementation logic in the Event hooks.

Yann: The hooks seem similiar to ring middlware, but middleware is defined on a per handler basis, and is dealing with non-realized input parameters (the request map).

### PR DESCRIPTION
**Pull request by yogsototh**
This PR provide two examples on how to use Java and/or Jar file to be used as hooks.

The method is not plug and play yet, but this is a good first step toward coding the `find-hooks` function.

Closes #159

### CODE REVIEW

**Comment by yogsototh** [comment]
Actually, the autoload only uses jar that provide classes which implement `ctia.Hook` java interface.

In my code, I transform such class into a Record extending the `Hook` Protocol.
The goal was to prevent javaist to use clojure data structure and let them use `java.util.HashMap<String,Object>`.

So if we want to add new hooks coded in Clojure in external jar, we could use a less friendly `reify` from the `ctia.Hook` java interface and I could get rid completely of the `Hook` Protocol.
But I believe we should privilege  the Clojure Protocol.

I didn't provided any example, yet, but I'm currently trying to provide jar generated from Clojure.
I will have to modify my `autoload-hooks` function slightly.

**Comment by gbuisson** [comment]
impressive! 👍

**Comment by AlexBaranosky** [comment]
You guys aren't big PR commit squashers?

When you want to rollback a pull request you may hate life having to rollback 12 commits.

Also from the perspective of the master branch, it can be nice to see each piece of logical functionality within its own commit.

**Comment by yogsototh** [comment]
Yes you're right, I'll squash most commits. Do you believe I should squash the complete PR into one commit?

**Comment by AlexBaranosky** [comment]
@yogsototh I (quickly) read through the commits and it seems like there is really only one "chunk of meaningful functionality" or "feature" being added here. For that reason I'd squash it all to one commit.

If there were two meaningful separate chunks of functionality, that might want to be reverted independently, then I'd do two commits, etc.

**Comment by polygloton** [comment]
I think you can remove the nested lein project files (like CHANGELOG, LICENSE, doc/, etc.).  If you don't strictly plan on using it, just delete it.  README might be useful for the example though.  The top level license, etc. will apply to all code in the repo.

**Comment by yogsototh** [comment]
I've removed all file which I believe aren't used. Most java file are given as example on how to generate the jar files. May be we could but these examples in another repository, but I also use these `jar` files to make my tests. So it might be a good idea to keep them in this repository.

**Comment by polygloton** [comment]
Looks good

**Pull request merged**
